# Generated by Django 5.2.6 on 2025-11-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_unlockslot_unlockbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlockslot',
            name='capacity',
        ),
    ]
