# Generated by Django 5.2.6 on 2025-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_unlockslot_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockbooking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterUniqueTogether(
            name='unlockbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unlockbooking',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
