# Generated by Django 5.2.6 on 2025-11-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_unlockbooking_options_and_more'),
        ('app', '0005_unlockbooking_subject_remove_unique'),
    ]

    operations = [
    ]
