# Generated by Django 5.2.6 on 2025-11-13 16:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_unlockbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockbooking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='unlockbooking',
            unique_together={('user', 'slot')},
        ),
        migrations.RemoveField(
            model_name='unlockbooking',
            name='subject',
        ),
    ]
