# Generated by Django 4.2.7 on 2025-11-18 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('attempt_id', models.CharField(help_text='Identifier from saved exam file (saved_at token).', max_length=64)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('graded_by', models.CharField(blank=True, max_length=150)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-graded_at'],
                'unique_together': {('user', 'attempt_id')},
            },
        ),
    ]
