# Generated by Django 5.2.8 on 2025-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_facultysubjectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, help_text="User's semester (e.g., semester1, semester2)", max_length=50, null=True),
        ),
    ]
