# Generated by Django 5.2.3 on 2025-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockslot',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Maximum number of students (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='unlockslot',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for this exam slot', null=True),
        ),
        migrations.AddField(
            model_name='unlockslot',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for this exam slot', null=True),
        ),
        migrations.AddField(
            model_name='unlockslot',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject for this exam slot (optional)', max_length=255, null=True),
        ),
    ]
