from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('register/', views.register_view,name='register'),
    path('login/', views.login_view,name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('dashboard/', views.dashboard,name='dashboard'),
    path('admin_login/', views.admin_login,name='admin_login'),
    path('Admin_dashboard/', views.admin_dashboard, name='Admin_dashboard'),
    path('faculty_login/', views.faculty_login, name='faculty_login'),
    path('faculty_dashboard/', views.faculty_dashboard, name='faculty_dashboard'),
    path('faculty_logout/', views.faculty_logout, name='faculty_logout'),
    path('faculty/results/', views.faculty_results, name='faculty_results'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/exams/', views.my_exams, name='my_exams'),
    path('profile/results/', views.exam_results_view, name='exam_results'),
    path('profile/exams/download/<str:filename>/', views.download_exam, name='download_exam'),
    path('profile/exams/download_multiple/', views.download_multiple_exams, name='download_multiple_exams'),
    path('unlock/', views.unlock_list, name='unlock_list'),
    path('api/unlock_slots/', views.api_unlock_slots, name='api_unlock_slots'),
    path('api/admin_create_slots/', views.api_admin_create_slots, name='api_admin_create_slots'),
    path('api/debug_unlocks/', views.api_debug_unlocks, name='api_debug_unlocks'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('save_exam/', views.save_exam_selection, name='save_exam'),
    path('notification_details/', views.notification_details, name='notification_details'),
    path('api/get_attendance/<int:slot_id>/', views.api_get_attendance, name='api_get_attendance'),
    path('api/update_attendance/', views.api_update_attendance, name='api_update_attendance'),
    path('api/update_attendance_bulk/', views.api_update_attendance_bulk, name='api_update_attendance_bulk'),
    path('api/generate_attendance_report/<int:slot_id>/', views.api_generate_attendance_report, name='api_generate_attendance_report'),
    path('api/generate_attendance_report_by_month/', views.api_generate_attendance_report_by_month, name='api_generate_attendance_report_by_month'),
    path('faculty_register/', views.faculty_register, name='faculty_register'),
    path('approve_request/', views.approve_request, name='approve_request'),
    path('download_exam_attendance/', views.download_exam_attendance, name='download_exam_attendance'),
    path('api/get_exam_dates_by_subject/', views.api_get_exam_dates_by_subject, name='api_get_exam_dates_by_subject'),
    path('api/get_subjects_by_date/', views.api_get_subjects_by_date, name='api_get_subjects_by_date'),
    path('api/get_subjects_for_date/', views.api_get_subjects_for_date, name='api_get_subjects_for_date'),
    path('api/submit_grade/', views.api_submit_grade, name='api_submit_grade'),
    path('api/delete_unlock_slot/<int:slot_id>/', views.api_delete_unlock_slot, name='api_delete_unlock_slot'),
    path('api/deactivate_unlock_slot/<int:slot_id>/', views.api_deactivate_unlock_slot, name='api_deactivate_unlock_slot'),
    path('api/update_unlock_slot/<int:slot_id>/', views.api_update_unlock_slot, name='api_update_unlock_slot'),
    path('api/bulk_delete_unlock_slots/', views.api_bulk_delete_unlock_slots, name='api_bulk_delete_unlock_slots'),
    path('api/reject_faculty/<str:username>/', views.api_reject_faculty, name='api_reject_faculty'),
]
